//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudDude1 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class MudDude1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static MudDude1 defaultInstance = ((MudDude1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MudDude1())));
        
        public static MudDude1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0.1.1")]
        public string STRING_SERVER_IP {
            get {
                return ((string)(this["STRING_SERVER_IP"]));
            }
            set {
                this["STRING_SERVER_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int INT_SERVER_PORT {
            get {
                return ((int)(this["INT_SERVER_PORT"]));
            }
            set {
                this["INT_SERVER_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("themudbot")]
        public string STRING_USERID {
            get {
                return ((string)(this["STRING_USERID"]));
            }
            set {
                this["STRING_USERID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("thembpass")]
        public string STRING_PASSWORD {
            get {
                return ((string)(this["STRING_PASSWORD"]));
            }
            set {
                this["STRING_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user")]
        public string STRING_LOGIN_USERNAME {
            get {
                return ((string)(this["STRING_LOGIN_USERNAME"]));
            }
            set {
                this["STRING_LOGIN_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("assword")]
        public string STRING_LOGIN_PASSWORD {
            get {
                return ((string)(this["STRING_LOGIN_PASSWORD"]));
            }
            set {
                this["STRING_LOGIN_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(N)onstop, (Q)uit, or (C)ontinue?")]
        public string STRING_PAUSE_STRING {
            get {
                return ((string)(this["STRING_PAUSE_STRING"]));
            }
            set {
                this["STRING_PAUSE_STRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(TOP)")]
        public string STRING_TOP_MENU {
            get {
                return ((string)(this["STRING_TOP_MENU"]));
            }
            set {
                this["STRING_TOP_MENU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@")]
        public char CHAR_TRIGGER {
            get {
                return ((char)(this["CHAR_TRIGGER"]));
            }
            set {
                this["CHAR_TRIGGER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!")]
        public char CHAR_TRIGGER2 {
            get {
                return ((char)(this["CHAR_TRIGGER2"]));
            }
            set {
                this["CHAR_TRIGGER2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/go mmud")]
        public string STRING_GO_COMMAND {
            get {
                return ((string)(this["STRING_GO_COMMAND"]));
            }
            set {
                this["STRING_GO_COMMAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please finish up and log off")]
        public string STRING_CLEANUP {
            get {
                return ((string)(this["STRING_CLEANUP"]));
            }
            set {
                this["STRING_CLEANUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int INT_CLEANUP_DURATION {
            get {
                return ((int)(this["INT_CLEANUP_DURATION"]));
            }
            set {
                this["INT_CLEANUP_DURATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IS_FIRST_RUN {
            get {
                return ((bool)(this["IS_FIRST_RUN"]));
            }
            set {
                this["IS_FIRST_RUN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int INT_EVILPOINTS_FOR_EVIL {
            get {
                return ((int)(this["INT_EVILPOINTS_FOR_EVIL"]));
            }
            set {
                this["INT_EVILPOINTS_FOR_EVIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int INT_RECONNECT_DELAY {
            get {
                return ((int)(this["INT_RECONNECT_DELAY"]));
            }
            set {
                this["INT_RECONNECT_DELAY"] = value;
            }
        }
    }
}
